[package]
name = "wit-tool-prototype"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"
tree-sitter = "0.25.10"
tree-sitter-wit = "0.2.0"

